### ISSUE TITLE
Switch to a better coverage calculator

### ISSUE THREAD

**Issue by mjwsteenbergen** [Fastjur/SEM-Project#113]

**Comment by mjwsteenbergen** [comment]
https://codecov.io/ looks like a good alternative.
With [free for a repository](https://codecov.io/pricing) and [easy to setup](https://github.com/codecov/example-java)

**Comment by Fastjur** [comment]
Will look at this :+1:

**Comment by TimvdLippe** [comment]
Jacoco + codecov = awesomesauce. +1 from me

**Comment by Fastjur** [comment]
I still don't get why coveralls is not good but okay

**Comment by TimvdLippe** [comment]
It spams your PR after every commit, whereas codecov only alters the top comment. I also find inspecting the coverage a lot easier than with coveralls.

**Comment by Fastjur** [comment]
Alright makes sense
