### ISSUE TITLE
Use InputHandler method of click handling instead of current one in SinglePlayerButton

### ISSUE THREAD

**Issue by Fastjur** [Fastjur/SEM-Project#26]

**Comment by Wolgo** [comment]
SinglePlayerButton extends Button, the onclick of button is called by doUpdate() which already uses `if(InputHandler.isLeftMouseButtonDown)` . Is there something wrong with this?

**Comment by grappigegovert** [comment]
Looks okay to me, there only are some unnecessary debug messages left

**Comment by Fastjur** [comment]
Hmm. It was my impression that `SinglePlayerButton` still used an old implementation because it spams the debug info. However the other button does to. This was probably some lag on my end when testing with other buttons. This does raise the question. Do we want the contains method to be spammed like this or should we prevent this?
