### ISSUE TITLE
Game over / Win screen should have a period where it doesn't go away when pressing a button.

### ISSUE THREAD

**Issue by Wolgo** [Fastjur/SEM-Project#95]
I keep spamming W to not die, so when i die the game over screen instantly closes.
Not sure about win Screen, but im assuming it has the same problem

**Comment by grappigegovert** [comment]
How about only going back to the main menu when pressing the 'enter' key?

**Comment by Wolgo** [comment]
Seems good. A new Issue has been opened to do that. Closing this one.
